apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=qrsmartmenu/backend
    argocd-image-updater.argoproj.io/yourtool.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^0.1.0-[0-9a-zA-Z]+$
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  project: default
  source:
    repoURL: https://github.com/SmartMenuProj/manifests-tmp.git
    path: applications/backend/overlays/dev
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true