apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argo-cd
spec:
  destination:
    name: https://kubernetes.default.svc
    namespace: dev
  project: default
  source:
    repoURL: https://github.com/SmartMenuProj/manifests-tmp.git
    path: applications/dev/backend
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
