apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: client=qrsmartmenu/frontend-client admin=qrsmartmenu/frontend-admin restaurant=qrsmartmenu/frontend
    argocd-image-updater.argoproj.io/client.update-strategy: latest
    argocd-image-updater.argoproj.io/client.allow-tags: regexp:^0.1.0-[0-9a-zA-Z]+$
    argocd-image-updater.argoproj.io/admin.update-strategy: latest
    argocd-image-updater.argoproj.io/admin.allow-tags: regexp:^0.1.0-[0-9a-zA-Z]+$
    argocd-image-updater.argoproj.io/restaurant.update-strategy: latest
    argocd-image-updater.argoproj.io/restaurant.allow-tags: regexp:^0.1.0-[0-9a-zA-Z]+$
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  project: default
  source:
    repoURL: https://github.com/SmartMenuProj/manifests-tmp.git
    path: applications/frontend/overlays/dev
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
